name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      id: workspace
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.5.0

      - name: Install project dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install project dependencies
        run: npm install --only=dev

      - name: Lint project
        run: npm run lint

  check-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install project dependencies
        run: npm install --only=dev

      - name: Check format
        run: npm run check-format

  run-tests:
    runs-on: ubuntu-latest
    needs: [lint, check-format]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install project dependencies
        run: npm install

      - name: Run tests
        run: npm test
