name: Bingle API CI pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.5.0

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

      - name: Install project dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        if: steps.setup.outputs.cache-hit != 'true'

      - name: Lint project
        run: npm run lint

  check-format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        if: steps.setup.outputs.cache-hit != 'true'

      - name: Check format
        run: npm run check-format

  run-tests:
    runs-on: ubuntu-latest
    needs: [lint, check-format]
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        if: steps.setup.outputs.cache-hit != 'true'

      - name: Run tests
        run: npm test
